branches: 
  - main
  - name: 1.x
    range: 1.x
    prerelease: false
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/git'