branches: 
  - main
plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: chore
          scope: deps
          release: patch
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/github'